## Functions: Defining your first function

In [2]:
def squareroot(x):
    return x**0.5

print(squareroot(9))

3.0


In [ ]:
answer = squareroot(25)
print(answer)

## Functions with no return statement

In [ ]:
def print_fancy(x):
    print("I'm printing '{}' using a function".format(x))

print_fancy(9)

In [ ]:
testing = print_fancy(232)
print(testing == None)
print(testing)

## Fibonacci Series with Functions



In [4]:
def fibonacci(num):
    """ 
    This functions prints fibonacci series upto num
    """
    f, s= 0, 1
    # WRITE YOUR CODE HERE
    # TODO
    while f<num:
        print(f)
        t = f+s
        f=s
        s=t
fibonacci(10)


0
1
1
2
3
5
8


## Global vs. Local Scope

In [12]:
import math
number = 5
sin = math.sin(number)
cos = math.cos(number)
print("Sin of {0} is {1} and cos is {2}".format(number, sin, cos))


Sin of 5 is -0.9589242746631385 and cos is 0.28366218546322625


### Local variables in a function are not visible outside the function

In [ ]:
def math_operations(num):
    sin_f = math.sin(num) # sin is a local variable
    cos_f = math.cos(num) # cos is a local variable

number = 10
math_operations(number)
print("Sin of {0} is {1} and cos is {2}".format(number, sin_f, cos_f))

### Local variables with same name as global variables do not get modified

In [ ]:
import math
def math_operations(num):
    sin = math.sin(num)
    cos = math.cos(num)

number = 5
sin = 5
cos = 20
math_operations(number)
print("sin: {}, cos: {}".format(sin, cos))

### Each function has it's own local variables and they are not accessible across in other places

In [ ]:
global_var = 20

def func1(num):
    local1 = 10
    local2 = 20
    print("I'm trying to print local variables {}, {} and a global variable {}".format(local1, local2, global_var))
    

def func2(num):
    local1 = 10
    print("I'm trying to print local variables {}, {} and a global variable{}".format(local1, local2, global_var))


## Named Arguments: defualt values for arguments

In [5]:
def calc_summary(var1, var2, var3, calc_mean = True):
    if calc_mean:
        return (var1+var2+var3)/3
    else:
        return var1+var2+var3

summary = calc_summary(2, 3, 4, calc_mean=False)
print(summary)
summary = calc_summary(2, 3, 4)
print(summary)

9
3.0


## String Operations

## List: Practice

## List: Basics and Accessing

## List: Sublist - x[a, b] means index a included and index b is not included

## List Assignment by Reference Practice

## List with for Loop

In [ ]:
lis = [2,3,5, 7]
for x in lis:
    print(x)

## Practice List with for loop #1 

Write a function that takes a list as input and returns the sum of squared values of each element in the list. 

Further, write a program that creates a sample list and prints the returned value of the above function. Verify if your function is working correctly. 


In [22]:
def sum_square(lis):
    """
    Returns the sum of squares of all elements in the list
    """
    ## WRITE YOUR CODE HERE
    ## TODO

lis= [2,4,5,6]
sum_square(lis)

## Practice List #2

Write a function that takes a list as input and returns the largest element in a list. 

Write a program that creates a sample list and prints the returned value of the above function. Verify if your function is working correctly.

## List: append(), insert(), remove(), and sort()

## List 'in' operator

## Ask a user to enter 10 words and use a list to save all words. Further, verify if there are words 'I', 'Love', 'Python' in them. 

In [ ]:

## The following piece of code could be helpful. 
if not all(['I' in evaluation, 'Love' in evaluation, 'Python' in evaluation]):
    print("You don't love Python enough. So sad. You are missing one or more words.")

## Fixed Type Arrays in Python (Available since Python 3.3)

In [8]:
import array
L = list(range(10))
A = array.array('i',L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
import array
L = list(range(10))
A = array.array('f',L)
A

array('f', [0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0])

# NumPy - Numerical Python 

## Importing numpy array

In [11]:
import numpy as np
np.__version__

'1.12.1'

Note: Some of the examples and content are from our text book PDSH Ch. 2 and from Mike Dunn at Notre Dame

## Fundamentals of NumPy Arrays


In [ ]:
list_of_ints = [0, 1, 2, 3, 4, 5]
np.array(list_of_ints)

### Accessing NumPy Array

### Forcing an Array's Data Type
You also have the option of forcing all NumPy array elements to have a specific data type.  Here I'll take a `list` of `float` objects and coerce them into `int` objects by specifying the **`dtype`** parameter on the `np.array` function.

In [ ]:
list_of_floats = [11.2, 57.6, 95.1]
np.array(list_of_floats, dtype=int)

<div class="alert alert-block alert-info">
<p>The <code>dtype</code> parameter can take many different values in additional these standard Python types: <code>int, float, bool, complex</code>.</p>

<p>For a complete list, you can visit <a href="https://docs.scipy.org/doc/numpy/user/basics.types.html" target="_blank">NumPy website.</a>
</div>

### Arrays can be Multi-Dimensional
NumPy arrays can be multi-dimensional. We'll start with a two dimensional array, which can be thought of a grid with x and y coordinates.

In [ ]:
# Don't focus on how this is being created. Just focus on the output.
two_dimensional_array = np.array([range(i, i + 3) for i in [2, 4, 6]])
two_dimensional_array

#### Accessing Multi-Dimensional Arrays

In [ ]:
# Get the first row (only specify an "x" coordinate)
print(two_dimensional_array[0])

# Get the last row
print(two_dimensional_array[2])

# Get the 1st column of the 2nd row.
print(two_dimensional_array[1][0])


## NumPy Array Attributes
Like all objects, NumPy Arrays have a set of attributes. Let's take moment to discuss some that you may find particularly helpful:

1. `ndim`
1. `shape`
1. `size`
1. `dtype`

To get started, let's create 3 arrays.

In [ ]:
x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

print("One Dimensional Array", x1, sep='\n')
print("Two Dimensional Array", x2, sep='\n')
print("Three Dimensional Array", x3, sep='\n')

### `ndim` Attribute
Returns the number of dimensions a given array has.

In [ ]:
print(x1.ndim, x2.ndim, x3.ndim)

### `shape` Attribute
Returns the number of elements a given dimension has. For our `x2` array we'd get this output:

```python
x2.shape
(3, 4)
```

If you look above, you'll see that the full represenation of our `x2` array was like this:

```
[[6 7 9 1]
 [3 4 1 2]
 [6 7 0 7]]
```

The `(3, 4)` returned by `x2.shape` is referring to the fact that our array had three "rows" and four "columns" in each row.

### `size` Attribute
Returns the total number of elements across all dimensions of an array.

So, for our one-dimensional array `size` will be 6.  
For our 2 dimensional array had dimensions of 3 & 4 elements, so `size` will be 12.  
Our 3 dimensional array had dimensions of 3, 4, and 5. Therefore it will have a total size of 60 elements.

In [ ]:
print("x1 size:", x1.size)
print("x2 size:", x2.size)
print("x3 size:", x3.size)

### `dtype` Attribute
Previously, we passed a `dtype` argument to the `np.array` constructor function to coerce the data type of the array's elements.

It comes about again here, but this time as an attribute of all NumPy array's. Unsurprisingly, it tells you the data type of the objects held inside the array.

In [ ]:
float_array = np.array([1, 2, 3.1])
float_array.dtype

### `itemsize` and `nbytes` Attributes
Other attributes include ``itemsize``, which lists the size (in bytes) of each array element, and ``nbytes``, which lists the total size (in bytes) of the array:

In [ ]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

In general, we expect that ``nbytes`` is equal to ``itemsize`` times ``size``.