## String Operations

In [1]:
string_one = 'Monty Python'

len(string_one)

12

In [12]:
x="Sean Patrick James"
x[-5:-2]

'Jam'

In [8]:
string_two = "I Love Python"
string_two.split()

['I', 'Love', 'Python']

In [34]:
str.split?

## List: Practice

In [13]:
list_one = [10,20,30,40,50]

## List: Basics and Accessing

In [14]:
list_one[0]

10

In [ ]:
list_one[4]

In [15]:
list_one[20]

IndexError: list index out of range

### Negative index accessing

In [16]:
list_one[-1]

50

In [17]:
list_one[-5]

10

## List: Sublist - x[a, b] means index a included and index b is not included

In [ ]:
list_one[1:3]

### Accessing the list in reverse order

In [32]:
print(x[::-1])
# ^ this is just "stepping" backwards
print(x[:3])
print(x[3:])
print(x[0:10:2])

semaJ kcirtaP naeS
Sea
n Patrick James
Sa ar


## List Assignment happens by reference 

In [33]:
list_one = [10,20,30,40,50]
list_two = list_one

list_two[0] = 100
print(list_one)

#altering a list will alter all variables that contain the list as well

[100, 20, 30, 40, 50]


## List sent as arguments to a function are also assigned by reference

In [34]:
def function_by_value(num_value):
    num_value = num_value + 1
    print(num_value)
    
number = 10
function_by_value(number)
print(number)

11
10


You should observe that the value _number_ has not changed, but we observe what happens when a list is sent as an argument 

In [35]:
def function_by_reference(lis):
    lis[0] = 5
    
my_list = [1,2,3,4]
function_by_reference(my_list)
print(my_list)

[5, 2, 3, 4]


We observe that `my_list` is sent to the function and gets modified within the function

### Heterogeneous Lists
So far, all of the elements in our two lists were the same type. Integers in `list_one` and strings in `list_two`. But this is not a requirement in Python.  You can place any number of different data types in a single list. For example: 

In [42]:
list_het = [True, "2", 3.0, 4]
print(type(list_het[0]))
print(type(list_het[2]))
print(type(list_het))

<class 'bool'>
<class 'float'>
<class 'list'>


## Using List in a for Loop

In [47]:
my_list = [20,30,50,70]
for x in my_list:
    print(x)
    
    # prints every element in the list; the list IS the range

20
30
50
70


## List: append(), insert(), remove(), and sort()

In [58]:
list=[1,2,3,4]
list.append(5)
print(list)

list2=[1,3]
list2.insert(2,5)
print(list2)

x=[1,5,7,2,3]
x.sort()
print(x)

x.sort(reverse=True)
print(x)

[1, 2, 3, 4, 5]
[1, 3, 5]
[1, 2, 3, 5, 7]
[7, 5, 3, 2, 1]


## List with 'in' operator

In [61]:
my_list = ['I', 'Love', 'Python']
'I' in my_list

my_heart=["Love"]
"Love" in my_heart


True

## Practice list

Ask a user to enter 5 words and use a list to save all words. Further, verify if there are words 'I', 'Love', 'Python' in them.

1. Create an empty list
2. Use append() function to keep appending to the list
3. Veify if the list contained any of the words 'I', 'Love', 'Python' 



In [ ]:
## The following piece of code could be helpful. 
if not all(['I' in my_list, 'Love' in my_list, 'Python' in my_list]):
    print("You don't love Python enough. So sad. You are missing one or more words.")

In [67]:
list=[]
for x in range(5):
    word=input("Enter a word!")
    list.append(word)
if not all(['I' in list, 'Love' in list, 'Python' in list]):
    print("You don't love Python enough. So sad. You are missing one or more words.")
else: print("You really like Python...Chill, dude.")


Enter a word!I
Enter a word!Love
Enter a word!Python
Enter a word!s
Enter a word!s
You really like Python...Chill, dude.


## Practice List with for loop #1 

Write a function that takes a list as input and returns the sum of squared values of each element in the list. 

Further, write a program that creates a sample list and prints the returned value of the above function. Verify if your function is working correctly. 


In [72]:
def sum_square(lis):
    list_ss=[(lis[0]**2),(lis[1]**2),(lis[2]**2),(lis[3]**2)]
    print(list_ss)

lis= [2,4,5,6]
sum_square(lis)

[4, 16, 25, 36]


## Practice List #2

Write a function that takes a list as input and returns the largest element in a list. 

Write a program that creates a sample list and prints the returned value of the above function. Verify if your function is working correctly.

In [77]:
x=0
def find_max(lis):
    if lis[0]>lis[1]:
        x=lis[0]
    elif lis[1]>lis[2]:
            x=lis[1]
    elif lis[2]>lis[3]:
        x=lis[2]
    elif lis[3]>lis[4]:
        x=lis[3]
    elif lis[4]>lis[5]:
        x=lis[4]
    else:
        x=lis[5]
    print("The largest number in your list is "+str(x)+"!")
    
    """
    Returns the maximum element of the list
    """
    ## Write your code here
    ## TODO

lis = [1,2,-3,1,3]
find_max(lis)

The largest number in your list is 2!


## List comprehension

Just think of it as a one-line way to create a list from another list.

Here it is adding a one to each number of `my_list` and storing the results in `compre_list`

In [ ]:
my_list = [1,2,3,4,5]

compre_list = [x+1 for x in my_list]

print(compre_list)

 ### Modified Practice List with for loop #1 with List Comprehension

## Fixed Type Arrays in Python (Available since Python 3.3)

In [8]:
import array
L = list(range(10))
A = array.array('i',L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
import array
L = list(range(10))
A = array.array('f',L)
A

array('f', [0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0])

# NumPy - Numerical Python 

## Importing numpy array

In [9]:
import numpy as np
np.__version__

'1.12.1'

Note: Some of the examples and content are from our text book PDSH Ch. 2

## Fundamentals of NumPy Arrays


### Creating NumPy array from a list

In [ ]:
list_of_ints = [0, 1, 2, 3, 4, 5]
np.array(list_of_ints)

### Creating NumPy array from scratch

In [ ]:
np.zeros(10)

In [ ]:
np.full(10, 3.14)

In [ ]:
np.arange(5,25, 5)

In [ ]:
np.arange?

### Accessing NumPy Array

### Forcing an Array's Data Type
You also have the option of forcing all NumPy array elements to have a specific data type.  Here I'll take a `list` of `float` objects and coerce them into `int` objects by specifying the **`dtype`** parameter on the `np.array` function.

In [ ]:
list_of_floats = [11.2, 57.6, 95.1]
np.array(list_of_floats, dtype=int)

<div class="alert alert-block alert-info">
<p>The <code>dtype</code> parameter can take many different values in additional these standard Python types: <code>int, float, bool, complex</code>.</p>

<p>For a complete list, you can visit <a href="https://docs.scipy.org/doc/numpy/user/basics.types.html" target="_blank">NumPy website.</a>
</div>

### Arrays can be Multi-Dimensional
NumPy arrays can be multi-dimensional. We'll start with a two dimensional array, which can be thought of a grid with x and y coordinates.

In [ ]:
# Don't focus on how this is being created. Just focus on the output.
two_dimensional_array = np.array([range(i, i + 3) for i in [2, 4, 6]])
two_dimensional_array

#### Accessing Multi-Dimensional Arrays

In [ ]:
# Get the first row (only specify an "x" coordinate)
print(two_dimensional_array[0])

# Get the last row
print(two_dimensional_array[2])

# Get the 1st column of the 2nd row.
print(two_dimensional_array[1][0])


## NumPy Array Attributes
Like all objects, NumPy Arrays have a set of attributes. Let's take moment to discuss some that you may find particularly helpful:

1. `ndim`
1. `shape`
1. `size`
1. `dtype`

To get started, let's create 3 arrays.

In [ ]:
x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

print("One Dimensional Array", x1, sep='\n')
print("Two Dimensional Array", x2, sep='\n')
print("Three Dimensional Array", x3, sep='\n')

### `ndim` Attribute
Returns the number of dimensions a given array has.

In [ ]:
print(x1.ndim, x2.ndim, x3.ndim)

### `shape` Attribute
Returns the number of elements a given dimension has. For our `x2` array we'd get this output:

```python
x2.shape
(3, 4)
```

If you look above, you'll see that the full represenation of our `x2` array was like this:

```
[[6 7 9 1]
 [3 4 1 2]
 [6 7 0 7]]
```

The `(3, 4)` returned by `x2.shape` is referring to the fact that our array had three "rows" and four "columns" in each row.

### `size` Attribute
Returns the total number of elements across all dimensions of an array.

So, for our one-dimensional array `size` will be 6.  
For our 2 dimensional array had dimensions of 3 & 4 elements, so `size` will be 12.  
Our 3 dimensional array had dimensions of 3, 4, and 5. Therefore it will have a total size of 60 elements.

In [ ]:
print("x1 size:", x1.size)
print("x2 size:", x2.size)
print("x3 size:", x3.size)

### `dtype` Attribute
Previously, we passed a `dtype` argument to the `np.array` constructor function to coerce the data type of the array's elements.

It comes about again here, but this time as an attribute of all NumPy array's. Unsurprisingly, it tells you the data type of the objects held inside the array.

In [ ]:
float_array = np.array([1, 2, 3.1])
float_array.dtype

### `itemsize` and `nbytes` Attributes
Other attributes include ``itemsize``, which lists the size (in bytes) of each array element, and ``nbytes``, which lists the total size (in bytes) of the array:

In [ ]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

In general, we expect that ``nbytes`` is equal to ``itemsize`` times ``size``.